import * as fs from 'fs';
import { resolve } from 'path';

let p = process.argv.pop();
if (p === 'auto') p = fs.readFileSync('.root-path')
if (p.endsWith('/')) p = p.substring(0, p.length-1)
console.log('Setting base route to', p);

const BaseRouteTS = `// Base Route | Generated by setup-routing.js
// See README.md
export const baseRoute = '${p}';
export default baseRoute;
`

fs.writeFileSync(resolve(process.cwd(), 'src', 'BaseRoute.ts'), BaseRouteTS);
fs.writeFileSync(resolve(process.cwd(),'.root-path'),`${p}/`)